/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ForRestaurantsRouteImport } from './routes/for.restaurants'
import { Route as ForHotelsRouteImport } from './routes/for.hotels'
import { Route as ForClinicsRouteImport } from './routes/for.clinics'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard.whatsapp'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardKnowledgeRouteImport } from './routes/dashboard.knowledge'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardHoursRouteImport } from './routes/dashboard.hours'
import { Route as DashboardEmaRouteImport } from './routes/dashboard.ema'
import { Route as DashboardContactsRouteImport } from './routes/dashboard.contacts'
import { Route as DashboardCatalogRouteImport } from './routes/dashboard.catalog'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardEmaIndexRouteImport } from './routes/dashboard.ema.index'
import { Route as DashboardEmaSettingsRouteImport } from './routes/dashboard.ema.settings'
import { Route as DashboardEmaReportsRouteImport } from './routes/dashboard.ema.reports'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForRestaurantsRoute = ForRestaurantsRouteImport.update({
  id: '/for/restaurants',
  path: '/for/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ForHotelsRoute = ForHotelsRouteImport.update({
  id: '/for/hotels',
  path: '/for/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClinicsRoute = ForClinicsRouteImport.update({
  id: '/for/clinics',
  path: '/for/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/dashboard/whatsapp',
  path: '/dashboard/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKnowledgeRoute = DashboardKnowledgeRouteImport.update({
  id: '/dashboard/knowledge',
  path: '/dashboard/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/dashboard/integrations',
  path: '/dashboard/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/dashboard/inbox',
  path: '/dashboard/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHoursRoute = DashboardHoursRouteImport.update({
  id: '/dashboard/hours',
  path: '/dashboard/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmaRoute = DashboardEmaRouteImport.update({
  id: '/dashboard/ema',
  path: '/dashboard/ema',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardContactsRoute = DashboardContactsRouteImport.update({
  id: '/dashboard/contacts',
  path: '/dashboard/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCatalogRoute = DashboardCatalogRouteImport.update({
  id: '/dashboard/catalog',
  path: '/dashboard/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBookingsRoute = DashboardBookingsRouteImport.update({
  id: '/dashboard/bookings',
  path: '/dashboard/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEmaIndexRoute = DashboardEmaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardEmaRoute,
} as any)
const DashboardEmaSettingsRoute = DashboardEmaSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardEmaRoute,
} as any)
const DashboardEmaReportsRoute = DashboardEmaReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardEmaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/ema': typeof DashboardEmaRouteWithChildren
  '/dashboard/hours': typeof DashboardHoursRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/for/clinics': typeof ForClinicsRoute
  '/for/hotels': typeof ForHotelsRoute
  '/for/restaurants': typeof ForRestaurantsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ema/reports': typeof DashboardEmaReportsRoute
  '/dashboard/ema/settings': typeof DashboardEmaSettingsRoute
  '/dashboard/ema/': typeof DashboardEmaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/hours': typeof DashboardHoursRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/for/clinics': typeof ForClinicsRoute
  '/for/hotels': typeof ForHotelsRoute
  '/for/restaurants': typeof ForRestaurantsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ema/reports': typeof DashboardEmaReportsRoute
  '/dashboard/ema/settings': typeof DashboardEmaSettingsRoute
  '/dashboard/ema': typeof DashboardEmaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/bookings': typeof DashboardBookingsRoute
  '/dashboard/catalog': typeof DashboardCatalogRoute
  '/dashboard/contacts': typeof DashboardContactsRoute
  '/dashboard/ema': typeof DashboardEmaRouteWithChildren
  '/dashboard/hours': typeof DashboardHoursRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/knowledge': typeof DashboardKnowledgeRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/for/clinics': typeof ForClinicsRoute
  '/for/hotels': typeof ForHotelsRoute
  '/for/restaurants': typeof ForRestaurantsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ema/reports': typeof DashboardEmaReportsRoute
  '/dashboard/ema/settings': typeof DashboardEmaSettingsRoute
  '/dashboard/ema/': typeof DashboardEmaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/dashboard/billing'
    | '/dashboard/bookings'
    | '/dashboard/catalog'
    | '/dashboard/contacts'
    | '/dashboard/ema'
    | '/dashboard/hours'
    | '/dashboard/inbox'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/settings'
    | '/dashboard/whatsapp'
    | '/for/clinics'
    | '/for/hotels'
    | '/for/restaurants'
    | '/dashboard/'
    | '/dashboard/ema/reports'
    | '/dashboard/ema/settings'
    | '/dashboard/ema/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/dashboard/billing'
    | '/dashboard/bookings'
    | '/dashboard/catalog'
    | '/dashboard/contacts'
    | '/dashboard/hours'
    | '/dashboard/inbox'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/settings'
    | '/dashboard/whatsapp'
    | '/for/clinics'
    | '/for/hotels'
    | '/for/restaurants'
    | '/dashboard'
    | '/dashboard/ema/reports'
    | '/dashboard/ema/settings'
    | '/dashboard/ema'
  id:
    | '__root__'
    | '/'
    | '/how-it-works'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/dashboard/billing'
    | '/dashboard/bookings'
    | '/dashboard/catalog'
    | '/dashboard/contacts'
    | '/dashboard/ema'
    | '/dashboard/hours'
    | '/dashboard/inbox'
    | '/dashboard/integrations'
    | '/dashboard/knowledge'
    | '/dashboard/settings'
    | '/dashboard/whatsapp'
    | '/for/clinics'
    | '/for/hotels'
    | '/for/restaurants'
    | '/dashboard/'
    | '/dashboard/ema/reports'
    | '/dashboard/ema/settings'
    | '/dashboard/ema/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBookingsRoute: typeof DashboardBookingsRoute
  DashboardCatalogRoute: typeof DashboardCatalogRoute
  DashboardContactsRoute: typeof DashboardContactsRoute
  DashboardEmaRoute: typeof DashboardEmaRouteWithChildren
  DashboardHoursRoute: typeof DashboardHoursRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardKnowledgeRoute: typeof DashboardKnowledgeRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  ForClinicsRoute: typeof ForClinicsRoute
  ForHotelsRoute: typeof ForHotelsRoute
  ForRestaurantsRoute: typeof ForRestaurantsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/restaurants': {
      id: '/for/restaurants'
      path: '/for/restaurants'
      fullPath: '/for/restaurants'
      preLoaderRoute: typeof ForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/hotels': {
      id: '/for/hotels'
      path: '/for/hotels'
      fullPath: '/for/hotels'
      preLoaderRoute: typeof ForHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/clinics': {
      id: '/for/clinics'
      path: '/for/clinics'
      fullPath: '/for/clinics'
      preLoaderRoute: typeof ForClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/dashboard/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/knowledge': {
      id: '/dashboard/knowledge'
      path: '/dashboard/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/dashboard/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/dashboard/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/hours': {
      id: '/dashboard/hours'
      path: '/dashboard/hours'
      fullPath: '/dashboard/hours'
      preLoaderRoute: typeof DashboardHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ema': {
      id: '/dashboard/ema'
      path: '/dashboard/ema'
      fullPath: '/dashboard/ema'
      preLoaderRoute: typeof DashboardEmaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/contacts': {
      id: '/dashboard/contacts'
      path: '/dashboard/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof DashboardContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/catalog': {
      id: '/dashboard/catalog'
      path: '/dashboard/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/bookings': {
      id: '/dashboard/bookings'
      path: '/dashboard/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof DashboardBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ema/': {
      id: '/dashboard/ema/'
      path: '/'
      fullPath: '/dashboard/ema/'
      preLoaderRoute: typeof DashboardEmaIndexRouteImport
      parentRoute: typeof DashboardEmaRoute
    }
    '/dashboard/ema/settings': {
      id: '/dashboard/ema/settings'
      path: '/settings'
      fullPath: '/dashboard/ema/settings'
      preLoaderRoute: typeof DashboardEmaSettingsRouteImport
      parentRoute: typeof DashboardEmaRoute
    }
    '/dashboard/ema/reports': {
      id: '/dashboard/ema/reports'
      path: '/reports'
      fullPath: '/dashboard/ema/reports'
      preLoaderRoute: typeof DashboardEmaReportsRouteImport
      parentRoute: typeof DashboardEmaRoute
    }
  }
}

interface DashboardEmaRouteChildren {
  DashboardEmaReportsRoute: typeof DashboardEmaReportsRoute
  DashboardEmaSettingsRoute: typeof DashboardEmaSettingsRoute
  DashboardEmaIndexRoute: typeof DashboardEmaIndexRoute
}

const DashboardEmaRouteChildren: DashboardEmaRouteChildren = {
  DashboardEmaReportsRoute: DashboardEmaReportsRoute,
  DashboardEmaSettingsRoute: DashboardEmaSettingsRoute,
  DashboardEmaIndexRoute: DashboardEmaIndexRoute,
}

const DashboardEmaRouteWithChildren = DashboardEmaRoute._addFileChildren(
  DashboardEmaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBookingsRoute: DashboardBookingsRoute,
  DashboardCatalogRoute: DashboardCatalogRoute,
  DashboardContactsRoute: DashboardContactsRoute,
  DashboardEmaRoute: DashboardEmaRouteWithChildren,
  DashboardHoursRoute: DashboardHoursRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardKnowledgeRoute: DashboardKnowledgeRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  ForClinicsRoute: ForClinicsRoute,
  ForHotelsRoute: ForHotelsRoute,
  ForRestaurantsRoute: ForRestaurantsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
